### PR TITLE
[Haskell] match deriving instance (..) without breaking data deriving

### PR DESCRIPTION
**Pull request by moodmosaic**
This fixes a bug introduced via 0d36dd1b18baa0e57474edc1853d901cd1887880

### CODE REVIEW

**Comment by moodmosaic** [comment]
This fix is the outcome of testing https://github.com/sublimehq/Packages/pull/2225 with a bunch of fairly-sized Haskell codebases.

If we get this one merged, and simplify the record syntax as per https://github.com/sublimehq/Packages/pull/2225#issuecomment-591228380, we should be able to ping Sublime HQ sometime soon. :heart_eyes:

**Comment by moodmosaic** [comment]
@FichteFoll, now that the upstream is merged, I'd like to tweet about it and mention you (and Daniel) in the tweet. If that's OK, could you please let me know your Twitter handle?

**Comment by FichteFoll** [comment]
Sure, that's appreciated. My twitter handle is the same as on Github, but I don't really use it, as you will see.

**Comment by moodmosaic** [comment]
https://twitter.com/nikosbaxevanis/status/1285886828634152960

**Pull request merged**
